joint_limits:
  joint1: {has_velocity_limits: true, max_velocity: 0.5, has_acceleration_limits: true, max_acceleration: 1.0}
  joint2: {has_velocity_limits: true, max_velocity: 0.5, has_acceleration_limits: true, max_acceleration: 1.0}
  joint3: {has_velocity_limits: true, max_velocity: 0.5, has_acceleration_limits: true, max_acceleration: 1.0}
  joint4: {has_velocity_limits: true, max_velocity: 0.7, has_acceleration_limits: true, max_acceleration: 1.4}
  joint5: {has_velocity_limits: true, max_velocity: 0.7, has_acceleration_limits: true, max_acceleration: 1.4}
  joint6: {has_velocity_limits: true, max_velocity: 0.7, has_acceleration_limits: true, max_acceleration: 1.4}
