h743_cmd_vel_bridge:
  ros__parameters:
    baud: 115200
    topic: /cmd_vel
    status_topic: /rs00/motor_status
    max_linear_speed: 0.10
    telemetry_period: 0.20

antbot_mapping_xbox:
  ros__parameters:
    use_sim_time: false
    max_linear_vel: 0.10
    max_angular_vel: 0.0
    topics.cmd_vel: /cmd_vel
